/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practica4smm;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author juanmaaf
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modo_dibujo = new javax.swing.ButtonGroup();
        barra_herramientas = new javax.swing.JToolBar();
        boton_linea = new javax.swing.JToggleButton();
        boton_rectangulo = new javax.swing.JToggleButton();
        boton_elipse = new javax.swing.JToggleButton();
        parte_inferior = new javax.swing.JPanel();
        panel_colores_relleno = new javax.swing.JPanel();
        panel_colores = new javax.swing.JPanel();
        boton_negro = new javax.swing.JButton();
        boton_rojo = new javax.swing.JButton();
        boton_azul = new javax.swing.JButton();
        boton_blanco = new javax.swing.JButton();
        boton_amarillo = new javax.swing.JButton();
        boton_verde = new javax.swing.JButton();
        panel_check = new javax.swing.JPanel();
        grosor = new javax.swing.JSpinner();
        alisar = new javax.swing.JCheckBox();
        transparencia = new javax.swing.JCheckBox();
        relleno = new javax.swing.JCheckBox();
        mover = new javax.swing.JCheckBox();
        barra_estado = new javax.swing.JLabel();
        lienzo = new practica4smm.Lienzo();
        menu_superior = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint Básico");

        barra_herramientas.setRollover(true);

        modo_dibujo.add(boton_linea);
        boton_linea.setIcon(new javax.swing.ImageIcon("/home/juanmaaf/NetBeansProjects/Practica4SMM/iconos/linea.png")); // NOI18N
        boton_linea.setFocusable(false);
        boton_linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_lineaActionPerformed(evt);
            }
        });
        barra_herramientas.add(boton_linea);

        modo_dibujo.add(boton_rectangulo);
        boton_rectangulo.setIcon(new javax.swing.ImageIcon("/home/juanmaaf/NetBeansProjects/Practica4SMM/iconos/rectangulo.png")); // NOI18N
        boton_rectangulo.setFocusable(false);
        boton_rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_rectanguloActionPerformed(evt);
            }
        });
        barra_herramientas.add(boton_rectangulo);

        modo_dibujo.add(boton_elipse);
        boton_elipse.setIcon(new javax.swing.ImageIcon("/home/juanmaaf/NetBeansProjects/Practica4SMM/iconos/elipse.png")); // NOI18N
        boton_elipse.setFocusable(false);
        boton_elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton_elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_elipseActionPerformed(evt);
            }
        });
        barra_herramientas.add(boton_elipse);

        getContentPane().add(barra_herramientas, java.awt.BorderLayout.PAGE_START);

        parte_inferior.setLayout(new java.awt.BorderLayout());

        panel_colores_relleno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_colores_relleno.setLayout(new java.awt.BorderLayout());

        panel_colores.setPreferredSize(new java.awt.Dimension(120, 75));
        panel_colores.setLayout(new java.awt.GridLayout(2, 3));

        boton_negro.setBackground(new java.awt.Color(0, 0, 0));
        boton_negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_negroActionPerformed(evt);
            }
        });
        panel_colores.add(boton_negro);

        boton_rojo.setBackground(new java.awt.Color(255, 0, 0));
        boton_rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_rojoActionPerformed(evt);
            }
        });
        panel_colores.add(boton_rojo);

        boton_azul.setBackground(new java.awt.Color(0, 0, 255));
        boton_azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_azulActionPerformed(evt);
            }
        });
        panel_colores.add(boton_azul);

        boton_blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_blancoActionPerformed(evt);
            }
        });
        panel_colores.add(boton_blanco);

        boton_amarillo.setBackground(new java.awt.Color(255, 255, 0));
        boton_amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_amarilloActionPerformed(evt);
            }
        });
        panel_colores.add(boton_amarillo);

        boton_verde.setBackground(new java.awt.Color(0, 255, 0));
        boton_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_verdeActionPerformed(evt);
            }
        });
        panel_colores.add(boton_verde);

        panel_colores_relleno.add(panel_colores, java.awt.BorderLayout.LINE_START);

        grosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                grosorStateChanged(evt);
            }
        });
        panel_check.add(grosor);

        alisar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        alisar.setText("Alisar");
        alisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alisarActionPerformed(evt);
            }
        });
        panel_check.add(alisar);

        transparencia.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        transparencia.setText("Transparencia");
        transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transparenciaActionPerformed(evt);
            }
        });
        panel_check.add(transparencia);

        relleno.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        relleno.setText("Relleno");
        relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoActionPerformed(evt);
            }
        });
        panel_check.add(relleno);

        mover.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        mover.setText("Mover");
        mover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moverActionPerformed(evt);
            }
        });
        panel_check.add(mover);

        panel_colores_relleno.add(panel_check, java.awt.BorderLayout.LINE_END);

        parte_inferior.add(panel_colores_relleno, java.awt.BorderLayout.CENTER);

        barra_estado.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        barra_estado.setText("Barra de Estado");
        barra_estado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        parte_inferior.add(barra_estado, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(parte_inferior, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.CENTER);

        menu_archivo.setText("Archivo");

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        menu_archivo.add(nuevo);

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        menu_archivo.add(abrir);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        menu_archivo.add(guardar);

        menu_superior.add(menu_archivo);

        setJMenuBar(menu_superior);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
            JOptionPane.showMessageDialog(this, "Archivo Abierto");
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
            JOptionPane.showMessageDialog(this, "Archivo Guardado");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        lienzo.borrarLienzo();
    }//GEN-LAST:event_nuevoActionPerformed

    private void rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoActionPerformed
        // TODO add your handling code here:
        lienzo.setRelleno(relleno.isSelected());
    }//GEN-LAST:event_rellenoActionPerformed

    private void boton_rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_rectanguloActionPerformed
        // TODO add your handling code here:
        if(boton_rectangulo.isSelected()){
            lienzo.setHerramienta(HerramientaDibujo.RECTANGULO);
            barra_estado.setText("Modo Rectángulo");
        }
    }//GEN-LAST:event_boton_rectanguloActionPerformed

    private void boton_lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_lineaActionPerformed
        // TODO add your handling code here:
        if(boton_linea.isSelected()){
            lienzo.setHerramienta(HerramientaDibujo.LINEA);
            barra_estado.setText("Modo Línea");
        }
    }//GEN-LAST:event_boton_lineaActionPerformed

    private void boton_elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_elipseActionPerformed
        // TODO add your handling code here:
        if(boton_elipse.isSelected()){
            lienzo.setHerramienta(HerramientaDibujo.ELIPSE);
            barra_estado.setText("Modo Elipse");
        }
    }//GEN-LAST:event_boton_elipseActionPerformed

    private void boton_negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_negroActionPerformed
        // TODO add your handling code here:
        lienzo.setColor(Color.black);
    }//GEN-LAST:event_boton_negroActionPerformed

    private void boton_rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_rojoActionPerformed
        // TODO add your handling code here:
        lienzo.setColor(Color.red);
    }//GEN-LAST:event_boton_rojoActionPerformed

    private void boton_azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_azulActionPerformed
        // TODO add your handling code here:
        lienzo.setColor(Color.blue);
    }//GEN-LAST:event_boton_azulActionPerformed

    private void boton_blancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_blancoActionPerformed
        // TODO add your handling code here:
        lienzo.setColor(Color.white);
    }//GEN-LAST:event_boton_blancoActionPerformed

    private void boton_amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_amarilloActionPerformed
        // TODO add your handling code here:
        lienzo.setColor(Color.yellow);
    }//GEN-LAST:event_boton_amarilloActionPerformed

    private void boton_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_verdeActionPerformed
        // TODO add your handling code here:
        lienzo.setColor(Color.green);
    }//GEN-LAST:event_boton_verdeActionPerformed

    private void moverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moverActionPerformed
        // TODO add your handling code here:
        lienzo.setMover(mover.isSelected());
    }//GEN-LAST:event_moverActionPerformed

    private void grosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_grosorStateChanged
        // TODO add your handling code here:
        lienzo.setGrosor((int) grosor.getValue());
    }//GEN-LAST:event_grosorStateChanged

    private void transparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transparenciaActionPerformed
        // TODO add your handling code here:
        lienzo.setModo_transparencia(transparencia.isSelected());
    }//GEN-LAST:event_transparenciaActionPerformed

    private void alisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisarActionPerformed
        // TODO add your handling code here:
        lienzo.setModo_alisado(alisar.isSelected());
    }//GEN-LAST:event_alisarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JCheckBox alisar;
    private javax.swing.JLabel barra_estado;
    private javax.swing.JToolBar barra_herramientas;
    private javax.swing.JButton boton_amarillo;
    private javax.swing.JButton boton_azul;
    private javax.swing.JButton boton_blanco;
    private javax.swing.JToggleButton boton_elipse;
    private javax.swing.JToggleButton boton_linea;
    private javax.swing.JButton boton_negro;
    private javax.swing.JToggleButton boton_rectangulo;
    private javax.swing.JButton boton_rojo;
    private javax.swing.JButton boton_verde;
    private javax.swing.JSpinner grosor;
    private javax.swing.JMenuItem guardar;
    private practica4smm.Lienzo lienzo;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenuBar menu_superior;
    private javax.swing.ButtonGroup modo_dibujo;
    private javax.swing.JCheckBox mover;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JPanel panel_check;
    private javax.swing.JPanel panel_colores;
    private javax.swing.JPanel panel_colores_relleno;
    private javax.swing.JPanel parte_inferior;
    private javax.swing.JCheckBox relleno;
    private javax.swing.JCheckBox transparencia;
    // End of variables declaration//GEN-END:variables
}
